const books={zoo:EVERPAGE_ZOO,bees:EVERPAGE_BEES};let currentBook=null,currentChapter=0;
const $=s=>document.querySelector(s);
const progress=JSON.parse(localStorage.getItem("everpageProgress")||"{}");
const favorites=JSON.parse(localStorage.getItem("everpageFavorites")||"[]");
function save(){localStorage.setItem("everpageProgress",JSON.stringify(progress));localStorage.setItem("everpageFavorites",JSON.stringify(favorites))}
function toast(msg){const e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),2200)}
function modal(id,show=true){const e=$("#"+id);e.classList.toggle("show",show);e.setAttribute("aria-hidden",String(!show))}
function openBook(key){currentBook=books[key];currentChapter=Math.min(progress[key]||0,currentBook.chapters.length-1);renderChapter();modal("readerModal",true);document.body.style.overflow="hidden"}
function closeModals(){document.querySelectorAll(".modal").forEach(e=>e.classList.remove("show"));document.body.style.overflow=""}
function renderChapter(){const c=currentBook.chapters[currentChapter];$("#readerSeries").textContent=currentBook.series;$("#readerTitle").textContent=currentBook.title;$("#chapterLabel").textContent="CHAPTER "+roman(currentChapter+1);$("#chapterTitle").textContent=c.title;$("#chapterText").innerHTML=c.text.map(p=>"<p>"+escapeHTML(p)+"</p>").join("");$("#progressLabel").textContent=(currentChapter+1)+" / "+currentBook.chapters.length;$("#prevBtn").disabled=currentChapter===0;$("#nextBtn").textContent=currentChapter===currentBook.chapters.length-1?"The End":"Next chapter →";progress[currentBook.key]=currentChapter;save()}
function next(){if(currentChapter<currentBook.chapters.length-1){currentChapter++;renderChapter();$(".reader").scrollIntoView({behavior:"smooth",block:"start"})}else toast("THE END — You finished this Everpage Original.")}
function prev(){if(currentChapter>0){currentChapter--;renderChapter()}else toast("You're already at Chapter One.")}
function roman(n){let s="";for(const [v,x] of [[20,"XX"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]])while(n>=v){s+=x;n-=v}return s}
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderBooks(){const g=$("#bookGrid");g.innerHTML=Object.values(books).map(b=>`<article class="book-card"><div class="cover ${b.cover}"><small>EVERPAGE ORIGINAL</small><b>${b.title}</b><small>20 CHAPTERS</small></div><div class="book-info"><div class="meta">${b.genre.toUpperCase()} · 20 CHAPTERS</div><h3>${b.title}</h3><p>${b.description}</p><button class="btn gold" data-action="open" data-book="${b.key}">Start reading</button></div></article>`).join("")}
function search(){modal("searchModal",true);$("#searchInput").focus();renderSearch("")}
function renderSearch(q){const term=q.toLowerCase().trim();let out=[];Object.values(books).forEach(b=>{if(!term||b.title.toLowerCase().includes(term)||b.genre.toLowerCase().includes(term))out.push(`<div class="result" data-action="open" data-book="${b.key}"><strong>${b.title}</strong><span>${b.genre} · 20 chapters</span></div>`);b.chapters.forEach((c,i)=>{if(term&&c.title.toLowerCase().includes(term))out.push(`<div class="result" data-action="chapter" data-book="${b.key}" data-chapter="${i}"><strong>${c.title}</strong><span>${b.title} · Chapter ${i+1}</span></div>`)})});$("#searchResults").innerHTML=out.length?out.join(""):`<p class="muted">No stories or chapters matched “${escapeHTML(q)}”.</p>`}
function profile(){const total=Object.values(books).reduce((n,b)=>n+b.chapters.length,0),read=Object.values(progress).reduce((n,v)=>n+Math.min(v+1,20),0);$("#profileStats").innerHTML=`<div class="stat"><strong>${read}</strong> chapters opened</div><div class="stat"><strong>${total}</strong> chapters available</div><div class="stat"><strong>02</strong> Everpage Originals</div>`;modal("profileModal",true)}
document.addEventListener("click",e=>{const a=e.target.closest("[data-action]");if(!a)return;const act=a.dataset.action;if(act==="open")openBook(a.dataset.book);if(act==="chapter"){closeModals();currentBook=books[a.dataset.book];currentChapter=+a.dataset.chapter;renderChapter();modal("readerModal",true);document.body.style.overflow="hidden"}if(act==="next")next();if(act==="prev")prev();if(act==="close")closeModals();if(act==="search")search();if(act==="profile")profile();if(act==="about")modal("aboutModal",true);if(act==="library")document.querySelector("#library").scrollIntoView({behavior:"smooth"});if(act==="home")window.scrollTo({top:0,behavior:"smooth"})});
$("#searchInput").addEventListener("input",e=>renderSearch(e.target.value));
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModals();if($("#readerModal").classList.contains("show")){if(e.key==="ArrowRight")next();if(e.key==="ArrowLeft")prev()}});
renderBooks();